import { describe, expect, it } from 'vitest';
import { findConventionPaths } from '../github/mapper';
import { isGeneratedFile } from '../agent/validate';

/**
 * Motivado por um caso real: um projeto TanStack Start recebeu commits escritos
 * no formato do Next.js e o preview parou de buildar. O repositorio DIZIA como
 * trabalhar nele — `AGENTS.md` na raiz e `src/routes/README.md` explicando o
 * roteamento por arquivo — e a extensao nao lia nenhum dos dois.
 */

describe('convencoes locais do repositorio', () => {
  it('acha README e AGENTS dentro de subdiretorio', () => {
    const achados = findConventionPaths([
      'README.md',
      'src/routes/README.md',
      'src/components/AGENTS.md',
      'src/App.tsx',
    ]);

    expect(achados).toContain('src/routes/README.md');
    expect(achados).toContain('src/components/AGENTS.md');
  });

  it('ignora o README da raiz — esse ja vai inteiro no prompt', () => {
    expect(findConventionPaths(['README.md', 'AGENTS.md'])).toEqual([]);
  });

  it('prioriza o que esta mais perto da raiz', () => {
    // Convencao de diretorio raso vale para mais arquivos; se algo tiver que
    // ficar de fora do teto, que seja o mais especifico.
    const achados = findConventionPaths([
      'a/b/c/d/README.md',
      'src/README.md',
    ]);
    expect(achados[0]).toBe('src/README.md');
  });

  it('nao confunde arquivo cujo nome apenas contem readme', () => {
    expect(findConventionPaths(['docs/READMEX.md', 'src/readme-antigo.md'])).toEqual([]);
  });
});

describe('arquivo gerado pela ferramentagem', () => {
  it('reconhece pelo cabecalho que o proprio arquivo escreve', () => {
    // O texto e' o do TanStack Router, verbatim.
    const cabecalho =
      '/* eslint-disable */\n// @ts-nocheck\n// This file was automatically generated by TanStack Router.\n' +
      '// You should NOT make any changes in this file as it will be overwritten.\n';
    expect(isGeneratedFile('src/routeTree.gen.ts', cabecalho)).toBe(true);
  });

  it('reconhece pela convencao `.gen.` mesmo sem ler o conteudo', () => {
    expect(isGeneratedFile('src/routeTree.gen.ts', null)).toBe(true);
    expect(isGeneratedFile('src/api/schema.gen.tsx', null)).toBe(true);
  });

  it('pega outras ferramentas pelo mesmo cabecalho, sem lista de nomes', () => {
    expect(isGeneratedFile('src/gql/types.ts', '// @generated by graphql-codegen\n')).toBe(true);
    expect(isGeneratedFile('src/db/schema.ts', '/* Auto-generated file. Do not edit. */\n')).toBe(true);
  });

  it('arquivo comum continua editavel', () => {
    // Barrar demais seria pior do que nao barrar: o agente ficaria sem poder
    // trabalhar em arquivo legitimo.
    expect(isGeneratedFile('src/App.tsx', 'export default function App() {}')).toBe(false);
    expect(isGeneratedFile('src/routes/index.tsx', null)).toBe(false);
    // "generated" no meio do arquivo nao conta: so o cabecalho declara.
    const tarde = `${'x\n'.repeat(400)}// this file was automatically generated`;
    expect(isGeneratedFile('src/util.ts', tarde)).toBe(false);
  });
});
